In [1]:
import numpy as np

In [2]:
arr_0D=np.array(42)

In [3]:
arr_0D

array(42)

In [4]:
arr_0D.shape

()

In [5]:
arr_0D.ndim

0

In [6]:
arr_1D=np.array([1,2,3,4,5])

In [7]:
arr_1D

array([1, 2, 3, 4, 5])

In [8]:
arr_1D.shape

(5,)

In [9]:
arr_1D.ndim

1

In [10]:
arr_2D=np.array([[1,2,3],[4,5,6]])

In [11]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr_2D.shape

(2, 3)

In [13]:
arr_2D.ndim

2

In [14]:
arr_3D = np.arange(1, 28).reshape(3, 3, 3)

In [15]:
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [16]:
arr_3D.shape

(3, 3, 3)

In [17]:
arr_3D.ndim

3

In [18]:
arr_4D = np.arange(1, 257).reshape(4, 4, 4, 4)

In [19]:
arr_4D

array([[[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12],
         [ 13,  14,  15,  16]],

        [[ 17,  18,  19,  20],
         [ 21,  22,  23,  24],
         [ 25,  26,  27,  28],
         [ 29,  30,  31,  32]],

        [[ 33,  34,  35,  36],
         [ 37,  38,  39,  40],
         [ 41,  42,  43,  44],
         [ 45,  46,  47,  48]],

        [[ 49,  50,  51,  52],
         [ 53,  54,  55,  56],
         [ 57,  58,  59,  60],
         [ 61,  62,  63,  64]]],


       [[[ 65,  66,  67,  68],
         [ 69,  70,  71,  72],
         [ 73,  74,  75,  76],
         [ 77,  78,  79,  80]],

        [[ 81,  82,  83,  84],
         [ 85,  86,  87,  88],
         [ 89,  90,  91,  92],
         [ 93,  94,  95,  96]],

        [[ 97,  98,  99, 100],
         [101, 102, 103, 104],
         [105, 106, 107, 108],
         [109, 110, 111, 112]],

        [[113, 114, 115, 116],
         [117, 118, 119, 120],
         [121, 122, 123, 124],
         [125, 126, 127

In [20]:
arr_4D.shape

(4, 4, 4, 4)

In [21]:
arr_4D.ndim

4

In [22]:
arr_5D = np.arange(1, 3126).reshape(5, 5, 5, 5, 5)

In [23]:
arr_5D

array([[[[[   1,    2,    3,    4,    5],
          [   6,    7,    8,    9,   10],
          [  11,   12,   13,   14,   15],
          [  16,   17,   18,   19,   20],
          [  21,   22,   23,   24,   25]],

         [[  26,   27,   28,   29,   30],
          [  31,   32,   33,   34,   35],
          [  36,   37,   38,   39,   40],
          [  41,   42,   43,   44,   45],
          [  46,   47,   48,   49,   50]],

         [[  51,   52,   53,   54,   55],
          [  56,   57,   58,   59,   60],
          [  61,   62,   63,   64,   65],
          [  66,   67,   68,   69,   70],
          [  71,   72,   73,   74,   75]],

         [[  76,   77,   78,   79,   80],
          [  81,   82,   83,   84,   85],
          [  86,   87,   88,   89,   90],
          [  91,   92,   93,   94,   95],
          [  96,   97,   98,   99,  100]],

         [[ 101,  102,  103,  104,  105],
          [ 106,  107,  108,  109,  110],
          [ 111,  112,  113,  114,  115],
          [ 116,  117,  11

In [24]:
arr_5D.shape

(5, 5, 5, 5, 5)

In [25]:
arr_5D.ndim

5

In [26]:
arr = np.array([20,25,30,35,40,45,50,55,60])

In [27]:
arr[1:5]

array([25, 30, 35, 40])

In [28]:
arr[1:8:2]

array([25, 35, 45, 55])

In [29]:
arr[4:]

array([40, 45, 50, 55, 60])

In [30]:
arr[3::3]

array([35, 50])

In [31]:
arr[:]

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

In [32]:
arr[::3]

array([20, 35, 50])

In [33]:
arr[8]

np.int64(60)

In [34]:
arr[-4]

np.int64(45)

In [35]:
arr[-7:-2]

array([30, 35, 40, 45, 50])

In [36]:
arr[-2:-7:-1]

array([55, 50, 45, 40, 35])

In [37]:
arr.dtype

dtype('int64')

In [38]:
arr_str=np.array(["Vansh","Ajay"])

In [39]:
arr_str.dtype

dtype('<U5')

In [40]:
arr[3]=37

In [41]:
arr

array([20, 25, 30, 37, 40, 45, 50, 55, 60])

In [42]:
x_arr=arr.view()

In [43]:
x_arr[3]=35

In [44]:
arr

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

In [45]:
y_arr=arr.copy()

In [46]:
y_arr[3]=37

In [47]:
arr

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

In [48]:
y_arr

array([20, 25, 30, 37, 40, 45, 50, 55, 60])

In [49]:
unsorted_arr=np.array([3,2,1,0])

In [50]:
sorted_arr = np.sort(unsorted_arr)

In [51]:
np.where(arr==50)

(array([6]),)

In [52]:
arr_1 = np.array([70, 80])
arr_2 = np.array([90,60])

In [53]:
arr_3 = arr_1+arr_2

In [54]:
arr_3

array([160, 140])

In [55]:
arr_4 = np.concatenate((arr_1, arr_2))

In [56]:
arr_4

array([70, 80, 90, 60])

In [57]:
arr_1s = np.array(['70', '80'])
arr_2s = np.array(['90','60'])

In [58]:
arr_3s = arr_1s+arr_2s

In [59]:
arr_3s

array(['7090', '8060'], dtype='<U4')

In [60]:
arr_4s = np.concatenate((arr_1s, arr_2s))

In [61]:
arr_4s

array(['70', '80', '90', '60'], dtype='<U2')

In [62]:
new_arr=np.array_split(arr_4,2)

In [63]:
new_arr

[array([70, 80]), array([90, 60])]

In [64]:
new_arr1=np.array_split(arr_4,4)

In [65]:
new_arr1

[array([70]), array([80]), array([90]), array([60])]

In [66]:
for x in arr:
    print(x)

20
25
30
35
40
45
50
55
60


In [67]:
for x in range(arr.size):
    print(arr[x])

20
25
30
35
40
45
50
55
60
